[tool.poetry]
name = "spotify-tracker"
version = "0.1.0"
description = ""
authors = ["Michael Dippel"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
spotipy = "^2.23.0"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
